apiVersion: v1
kind: Service
metadata:
  name: {{ include "duoauthproxy-radius-simple.fullname" . }}
  labels:
    {{- include "duoauthproxy-radius-simple.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: radius
      nodePort: {{ .Values.service.port }}
      protocol: UDP
      name: radius
  selector:
    {{- include "duoauthproxy-radius-simple.selectorLabels" . | nindent 4 }}
