apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "duoauthproxy-radius-simple.fullname" . }}
  labels:
    {{- include "duoauthproxy-radius-simple.labels" . | nindent 4 }}
data:
  authproxy.cfg: |
{{- include "duoauthproxy-radius-simple.config" . | nindent 4 }}