duo:
  ikey: ""
  skey: ""
  apiHost: ""
  radiusIP: ""
  radiusSecret: ""
  failmode: "secure"
  debug: "true"

replicaCount: 2

image:
  repository: docker-snapshot.cernerrepos.net/commwx/duoauthproxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  port: 1812

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
